export const GET_RECIPES_CATEGORIES_REQUEST = "GET_RECIPES_CATEGORIES_REQUEST";
export const GET_RECIPES_CATEGORIES_SUCCESS = "GET_RECIPES_CATEGORIES_SUCCESS";
export const GET_RECIPES_CATEGORIES_FAIL = "GET_RECIPES_CATEGORIES_FAIL";

export const FILTER_RECIPES_BY_CATEGORIES_REQUEST = "FILTER_RECIPES_BY_CATEGORIES_REQUEST";
export const FILTER_RECIPES_BY_CATEGORIES_SUCCESS = "FILTER_RECIPES_BY_CATEGORIES_SUCCESS";
export const FILTER_RECIPES_BY_CATEGORIES_FAIL = "FILTER_RECIPES_BY_CATEGORIES_FAIL";

export const GET_LATEST_RECIPES_REQUEST = "GET_LATEST_RECIPES_REQUEST";
export const GET_LATEST_RECIPES_SUCCESS = "GET_LATEST_RECIPES_SUCCESS";
export const GET_LATEST_RECIPES_FAIL = "GET_LATEST_RECIPES_FAIL";

export const GET_MEAL_REQUEST = "GET_MEAL_REQUEST";
export const GET_MEAL_SUCCESS = "GET_MEAL_SUCCESS";
export const GET_MEAL_FAIL = "GET_MEAL_FAIL";

export const GET_ALPHABET_REQUEST = "GET_ALPHABET_REQUEST";
export const GET_ALPHABET_SUCCESS = "GET_ALPHABET_SUCCESS";
export const GET_ALPHABET_FAIL = "GET_ALPHABET_FAIL";