export const GET_RECIPES_CATEGORIES_REQUEST = "GET_RECIPES_CATEGORIES_REQUEST";
export const GET_RECIPES_CATEGORIES_SUCCESS = "GET_RECIPES_CATEGORIES_SUCCESS";
export const GET_RECIPES_CATEGORIES_FAIL = "GET_RECIPES_CATEGORIES_FAIL";

export const FILTER_RECIPES_BY_CATEGORIES_REQUEST = "FILTER_RECIPES_BY_CATEGORIES_REQUEST";
export const FILTER_RECIPES_BY_CATEGORIES_SUCCESS = "FILTER_RECIPES_BY_CATEGORIES_SUCCESS";
export const FILTER_RECIPES_BY_CATEGORIES_FAIL = "FILTER_RECIPES_BY_CATEGORIES_FAIL";