export const GET_RECIPES_CATEGORIES_REQUEST = "GET_RECIPES_CATEGORIES_REQUEST";
export const GET_RECIPES_CATEGORIES_SUCCESS = "GET_RECIPES_CATEGORIES_SUCCESS";
export const GET_RECIPES_CATEGORIES_FAIL = "GET_RECIPES_CATEGORIES_FAIL";
